version: '3.2'

services:

  skylight-cucs:
    privileged: true
    build: .
    environment:
      - DISPLAY=host.docker.internal:0
    network_mode: host
    command: cucs

  skylight-vsm:
    build: .
    network_mode: host
    command: vsm-simulation

  # skylight-uav:
  #   build: .
  #   network_mode: host
  #   command: uav-simulation

